# Generated by Django 4.2.20 on 2025-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
